src/Entity/API.php
<?php

namespace App\Entity;

use App\Repository\APIRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Gedmo\Mapping\Annotation as Gedmo;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;


/**
 * @ORM\Entity(repositoryClass=APIRepository::class)
 * @UniqueEntity(fields={"name"}, message="Une API possède déjà ce nom")
 */
class API
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $name;

    /**
     * @ORM\Column(type="text")
     */
    private $description;

    /**
     * @ORM\Column(type="text")
     */
    private $url;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $category;

    /**
     * @var \DateTimeInterface $updatedAt
     *
     * @Gedmo\Timestampable(on="create")
     * @ORM\Column(type="datetime")
     */
    private $updatedAt;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $api_key;

    /**
     * @ORM\OneToMany(targetEntity=BugReport::class, mappedBy="api", orphanRemoval=true)
     */
    private $bugReports;

    public function __construct()
    {
        $this->bugReports = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getUrl(): ?string
    {
        return $this->url;
    }

    public function setUrl(string $url): self
    {
        $this->url = $url;

        return $this;
    }

    public function getCategory(): ?string
    {
        return $this->category;
    }

    public function setCategory(string $category): self
    {
        $this->category = $category;

        return $this;
    }

    public function getUpdatedAt(): ?\DateTimeInterface
    {
        return $this->updatedAt;
    }

    public function setUpdatedAt(\DateTimeInterface $updatedAt): self
    {
        $this->updatedAt = $updatedAt;

        return $this;
    }

    public function getApiKey(): ?string
    {
        return $this->api_key;
    }

    public function setApiKey(string $api_key): self
    {
        $this->api_key = $api_key;

        return $this;
    }

    /**
     * @return Collection|BugReport[]
     */
    public function getBugReports(): Collection
    {
        return $this->bugReports;
    }

    public function addBugReport(BugReport $bugReport): self
    {
        if (!$this->bugReports->contains($bugReport)) {
            $this->bugReports[] = $bugReport;
            $bugReport->setApi($this);
        }

        return $this;
    }

    public function removeBugReport(BugReport $bugReport): self
    {
        if ($this->bugReports->contains($bugReport)) {
            $this->bugReports->removeElement($bugReport);
            // set the owning side to null (unless already changed)
            if ($bugReport->getApi() === $this) {
                $bugReport->setApi(null);
            }
        }

        return $this;
    }
}

src/Entity/ApiCreator.php
<?php

namespace App\Entity;

use App\Repository\ApiCreatorRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=ApiCreatorRepository::class)
 */
class ApiCreator
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $api_id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $full_name;

    /**
     * @ORM\ManyToMany(targetEntity=ApiProgram::class, inversedBy="apiCreators")
     */
    private $programs;

    public function __construct()
    {
        $this->programs = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getApiId(): ?string
    {
        return $this->api_id;
    }

    public function setApiId(string $api_id): self
    {
        $this->api_id = $api_id;

        return $this;
    }

    public function getFullName(): ?string
    {
        return $this->full_name;
    }

    public function setFullName(string $full_name): self
    {
        $this->full_name = $full_name;

        return $this;
    }

    /**
     * @return Collection|ApiProgram[]
     */
    public function getPrograms(): Collection
    {
        return $this->programs;
    }

    public function addProgram(ApiProgram $program): self
    {
        if (!$this->programs->contains($program)) {
            $this->programs[] = $program;
        }

        return $this;
    }

    public function removeProgram(ApiProgram $program): self
    {
        if ($this->programs->contains($program)) {
            $this->programs->removeElement($program);
        }

        return $this;
    }
}

src/Form/APIType.php
<?php

namespace App\Form;

use App\Entity\API;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class APIType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('name')
            ->add('description')
            ->add('url')
            ->add('category')
            ->add('apiKey')
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => API::class,
        ]);
    }
}

src/Controller/APIController.php
<?php

namespace App\Controller;

use App\Entity\API;
use App\Form\APIType;
use App\Repository\APIRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/api", name="api_")
 */
class APIController extends AbstractController
{
    /**
     * @Route("/", name="index", methods={"GET"})
     * @param APIRepository $apiRepository
     * @return Response
     */
    public function index(APIRepository $apiRepository): Response
    {
        return $this->render('api/index.html.twig', [
            'apis' => $apiRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="new", methods={"GET","POST"})
     * @param Request $request
     * @return Response
     */
    public function new(Request $request): Response
    {
        $api = new API();
        $form = $this->createForm(APIType::class, $api);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($api);
            $entityManager->flush();

            return $this->redirectToRoute('api_index');
        }

        return $this->render('api/new.html.twig', [
            'api' => $api,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{api}/edit", name="edit", methods={"GET","POST"})
     * @param Request $request
     * @param API $api
     * @return Response
     */
    public function edit(Request $request, API $api): Response
    {
        $form = $this->createForm(APIType::class, $api);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('api_index');
        }

        return $this->render('api/edit.html.twig', [
            'api' => $api,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="delete", methods={"DELETE"})
     * @param Request $request
     * @param API $api
     * @return Response
     */
    public function delete(Request $request, API $api): Response
    {
        if ($this->isCsrfTokenValid('delete'.$api->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($api);
            $entityManager->flush();
        }

        return $this->redirectToRoute('api_index');
    }
}

templates/api/_bug_report_form.html.twig
{{ form_start(bugReport, {
    'attr': {
        'class': 'form-group',
        'novalidate': 'novalidate'
    }}) }}
    {{ form_label(bugReport.message) }}
    {{ form_widget(bugReport.message) }}
    <button type="submit" class="btn btn-lg btn-outline-info">Je préviens le site</button>
{{ form_end(bugReport) }}

templates/api/_delete_form.html.twig
<form method="post" action="{{ path('api_delete', {'id': api.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ api.id) }}">
    <button class="btn">Delete</button>
</form>

templates/api/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/api/api_show_program.html.twig
{% extends 'base.html.twig' %}

{% block title %}API{% endblock %}

{% block body %}

    <section class="all_episodes container">
        {% if program is defined %}
            <article class="program_details row">
                <div class="col-lg-4">
                    <img src="{{ program.poster }}" alt="poster">
                </div>
                <div class="col-lg-8">
                    <h1>{{ program.title }} - <span>{{ program.year }} - {{ program.endYear }}</span></h1>
                    <p class="category">{% for category in program.categories %}{{ category.name|capitalize }} | {% endfor %}</p>
                    <blockquote>{{ program.summary }}</blockquote>
                    <p class="creator">Created by{% for creator in program.creators %} {{ creator.fullName }} | {% endfor %}</p>
                    <p class="actor">With {% for actor in program.actors %}{{ actor.name }} | {% endfor %}</p>
                    <cite class="awards">{{ program.awards }}</cite>
                </div>
            </article>
            <article class="seasons">
                {% for season in program.seasons %}
                    <button type="button" class="btn" data-toggle="collapse" data-target="#season_{{ season.number }}">Season {{ season.number }}</button>
                    <div id="season_{{ season.number }}" class="collapse row">
                        {% for episode in season.episodes  %}
                            <div class="col-md-4 col-lg-3">
                                <form method="POST" id="mada">
                                    <p>{{ episode.number }} - {{ episode.title }}</p>
                                    <button type="submit">
                                        <img src="{{ episode.poster }}" alt="" class="img-fluid">
                                        <input type="hidden" name="get_episode_details" value="{{ episode.id }}">
                                    </button>
                                    <em>{{ episode.released }}</em>
                                </form>
                            </div>
                        {% endfor %}
                    </div>
                {% endfor %}
            </article>
        {% endif %}
        <footer class="container d-flex justify-content-between">
            <a href="{{ path('api_index') }}">Retour aux APIs</a>
            <a href="{{ path('explorer_index') }}">Retour à l'accueil</a>
        </footer>
    </section>
{#
    {% if is_granted("ROLE_ADMIN") %}
        {{ include('api/_delete_form.html.twig') }}
    {% endif %}
#}
{% endblock %}

templates/api/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit API{% endblock %}

{% block body %}
    <h1>Editer l'API</h1>

    {{ include('api/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('api_index') }}">back to list</a>

    {{ include('api/_delete_form.html.twig') }}
{% endblock %}

templates/api/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}API index{% endblock %}

{% block body %}
    <section class="container-fluid" id="api_index">
        <h1>API index</h1>

        <table class="table">
            <thead>
            <tr>
                <th>Nom</th>
                <th>Description</th>
                <th>Url</th>
                <th>Categorie</th>
                <th>Dernière MaJ</th>
                <th>Actions</th>
            </tr>
            </thead>
            <tbody>
            {% for api in apis %}
                <tr>
                    <td>{{ api.name }}</td>
                    <td>{{ api.description }}</td>
                    <td><a href="{{ api.url }}">{{ api.url }}</a></td>
                    <td>{{ api.category }}</td>
                    <td>{{ api.updatedAt|date('d/m/Y')}}</td>
                    <td>
                        <a href="{{ path('api_IMDB_show') }}">explorer</a>
                        {% if is_granted('ROLE_ADMIN') %}
                            <a href="{{ path('api_edit', {'api': api.id}) }}">editer</a>
                        {% endif %}
                    </td>
                </tr>
            {% else %}
                <tr>
                    <td colspan="6">no records found</td>
                </tr>
            {% endfor %}
            </tbody>
        </table>

        {% if is_granted('ROLE_ADMIN') %}
            <a href="{{ path('api_new') }}">Create new</a>
        {% endif %}

    </section>

{% endblock %}

templates/api/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New API{% endblock %}

{% block body %}
    <h1>Ajouter une API</h1>

    {{ include('api/_form.html.twig') }}

    <a href="{{ path('api_index') }}">back to list</a>
{% endblock %}

templates/api/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}API{% endblock %}

{% block body %}
{#
    <article>
        <h2>Endpoints Disponibles</h2>
        <ul>
            <li><code></code></li>
            <li><code></code></li>
            <li><code></code></li>
            <x
#}
    {% if formSearch is defined %}
        <section class="container text-center" id="search_serie">
            <h1 class="mb-5">Bienvenue sur {{ api.name }}</h1>


            {{ form_start(formSearch, {
                'attr': {
                    'class': 'form-group',
                    'novalidate': 'novalidate'
                }}) }}
            {{ form_label(formSearch.searchSerie) }}
            {{ form_widget(formSearch.searchSerie) }}
            {{ form_end(formSearch) }}
        </section>

        {% if bugReport is defined %}
            <section class="container text-center" id="bug_report">
                {% include '_bug_report_form.html.twig' %}
            </section>
        {% endif %}
    {% endif %}

    {% if programs is defined %}
        <section class="container" id="get_program_title">

            <h2>Résultat de la recherche</h2>

            <article class="row">
                {% for result in programs.results %}
                    <a href="">
                        <figure class="col-md-4 col-lg-3">
                            <figcaption>{{ result.title }}</figcaption>
                            <img src="{{ result.image }}" alt="">
                        </figure>
                    </a>
                {% else %}
                    Aucune série trouvée
                {% endfor %}
            </article>
        </section>
    {% endif %}


    <section class="container d-flex justify-content-between">
        <a href="{{ path('api_index') }}">Retour aux APIs</a>
        <a href="{{ path('explorer_index') }}">Retour à l'accueil</a>
    </section>
{% endblock %}